_VALID_LANGS = {"es", "en", "zh", "hi"}

_TRANSLATIONS = {
    "es": {
        "no_autenticado": "No autenticado",
        "solo_imagenes": "Solo se permiten imágenes (JPEG/PNG)",
        "imagen_muy_grande": "La imagen no puede superar los 10 MB",
        "diagnostico_encolado": "Diagnóstico encolado en posición {position}",
        "no_permiso_sesion": "No tienes permiso para acceder a esta sesión",
        "no_permiso_eliminar": "No tienes permiso para eliminar esta sesión",
        "no_permiso_renombrar": "No tienes permiso para renombrar esta sesión",
        "ruta_no_existe": "La ruta no existe.",
        "dataset_no_encontrado": "No se encontró la ruta del dataset original.",
        "recalculo_iniciado": "Recálculo iniciado.",
        "sesion_no_comparada": "Aún no se ha comparado esta sesión.",
        "ruta_externa_invalida": "La ruta del dataset externo no es válida.",
        "validacion_externa_iniciada": "Validación Externa iniciada.",
        "validacion_externa_encolada": "Validación Externa encolada como trabajo #{job_id}",
        "sin_resultados_externos": "Aún no hay resultados de validación externa.",
        "entrenamiento_encolado": "Entrenamiento encolado como trabajo #{job_id}",
        "esperando_logs": "Esperando...",
        "resultados_no_encontrados": "Resultados no encontrados",
        "label_pneumonia": "Neumonía",
        "label_normal": "Normal",
        "xai_original": "Radiografía Original",
        "xai_saliency": "Saliency Map",
        "xai_smoothgrad": "SmoothGrad",
        "xai_overlay": "{method} Overlay",
        "pdf_title": "X-Ray AI Consultant - Reporte de Diagnóstico",
        "pdf_date": "Fecha:",
        "pdf_model": "Modelo de IA Utilizado:",
        "pdf_diagnosis": "DIAGNÓSTICO: {label}",
        "pdf_confidence": "Nivel de Confianza: {confidence}%",
        "pdf_original": "Radiografía Original",
        "pdf_heatmap": "Mapa de Calor (XAI)",
        "pdf_error_images": "Error cargando imágenes",
        "chat_apikey_error": "GROQ_API_KEY no configurada",
    },
    "en": {
        "no_autenticado": "Not authenticated",
        "solo_imagenes": "Only images are allowed (JPEG/PNG)",
        "imagen_muy_grande": "Image cannot exceed 10 MB",
        "diagnostico_encolado": "Diagnosis queued at position {position}",
        "no_permiso_sesion": "You don't have permission to access this session",
        "no_permiso_eliminar": "You don't have permission to delete this session",
        "no_permiso_renombrar": "You don't have permission to rename this session",
        "ruta_no_existe": "The path does not exist.",
        "dataset_no_encontrado": "Original dataset path not found.",
        "recalculo_iniciado": "Recalculation started.",
        "sesion_no_comparada": "This session has not been compared yet.",
        "ruta_externa_invalida": "The external dataset path is not valid.",
        "validacion_externa_iniciada": "External Validation started.",
        "validacion_externa_encolada": "External Validation queued as job #{job_id}",
        "sin_resultados_externos": "No external validation results yet.",
        "entrenamiento_encolado": "Training queued as job #{job_id}",
        "esperando_logs": "Waiting...",
        "resultados_no_encontrados": "Results not found",
        "label_pneumonia": "Pneumonia",
        "label_normal": "Normal",
        "xai_original": "Original X-ray",
        "xai_saliency": "Saliency Map",
        "xai_smoothgrad": "SmoothGrad",
        "xai_overlay": "{method} Overlay",
        "pdf_title": "X-Ray AI Consultant - Diagnosis Report",
        "pdf_date": "Date:",
        "pdf_model": "AI Model Used:",
        "pdf_diagnosis": "DIAGNOSIS: {label}",
        "pdf_confidence": "Confidence Level: {confidence}%",
        "pdf_original": "Original X-ray",
        "pdf_heatmap": "XAI Heatmap",
        "pdf_error_images": "Error loading images",
        "chat_apikey_error": "GROQ_API_KEY not configured",
    },
    "zh": {
        "no_autenticado": "未认证",
        "solo_imagenes": "只允许图像文件 (JPEG/PNG)",
        "imagen_muy_grande": "图像不能超过10MB",
        "diagnostico_encolado": "诊断已排队，位置 {position}",
        "no_permiso_sesion": "您无权访问此会话",
        "no_permiso_eliminar": "您无权删除此会话",
        "no_permiso_renombrar": "您无权重命名此会话",
        "ruta_no_existe": "路径不存在。",
        "dataset_no_encontrado": "未找到原始数据集路径。",
        "recalculo_iniciado": "重新计算已开始。",
        "sesion_no_comparada": "此会话尚未比较。",
        "ruta_externa_invalida": "外部数据集路径无效。",
        "validacion_externa_iniciada": "外部验证已开始。",
        "validacion_externa_encolada": "外部验证已排队，作业 #{job_id}",
        "sin_resultados_externos": "尚无外部验证结果。",
        "entrenamiento_encolado": "训练已排队，作业 #{job_id}",
        "esperando_logs": "等待中...",
        "resultados_no_encontrados": "未找到结果",
        "label_pneumonia": "肺炎",
        "label_normal": "正常",
        "xai_original": "原始X光片",
        "xai_saliency": "显著性图",
        "xai_smoothgrad": "平滑梯度",
        "xai_overlay": "{method} 叠加图",
        "pdf_title": "X-Ray AI Consultant - 诊断报告",
        "pdf_date": "日期:",
        "pdf_model": "使用的人工智能模型:",
        "pdf_diagnosis": "诊断: {label}",
        "pdf_confidence": "置信度: {confidence}%",
        "pdf_original": "原始X光片",
        "pdf_heatmap": "XAI 热力图",
        "pdf_error_images": "加载图像时出错",
        "chat_apikey_error": "GROQ_API_KEY 未配置",
    },
    "hi": {
        "no_autenticado": "प्रमाणित नहीं",
        "solo_imagenes": "केवल छवियां अनुमत हैं (JPEG/PNG)",
        "imagen_muy_grande": "छवि 10 MB से अधिक नहीं हो सकती",
        "diagnostico_encolado": "निदान कतार में स्थान {position}",
        "no_permiso_sesion": "आपके पास इस सत्र तक पहुंचने की अनुमति नहीं है",
        "no_permiso_eliminar": "आपके पास इस सत्र को हटाने की अनुमति नहीं है",
        "no_permiso_renombrar": "आपके पास इस सत्र का नाम बदलने की अनुमति नहीं है",
        "ruta_no_existe": "पथ मौजूद नहीं है।",
        "dataset_no_encontrado": "मूल डेटासेट पथ नहीं मिला।",
        "recalculo_iniciado": "पुनर्गणना शुरू हुई।",
        "sesion_no_comparada": "इस सत्र की अभी तुलना नहीं हुई है।",
        "ruta_externa_invalida": "बाहरी डेटासेट पथ मान्य नहीं है।",
        "validacion_externa_iniciada": "बाहरी सत्यापन शुरू हुआ।",
        "validacion_externa_encolada": "बाहरी सत्यापन कतार में कार्य #{job_id}",
        "sin_resultados_externos": "अभी तक कोई बाहरी सत्यापन परिणाम नहीं।",
        "entrenamiento_encolado": "प्रशिक्षण कतार में कार्य #{job_id}",
        "esperando_logs": "प्रतीक्षा...",
        "resultados_no_encontrados": "परिणाम नहीं मिले",
        "label_pneumonia": "न्यूमोनिया",
        "label_normal": "सामान्य",
        "xai_original": "मूल एक्स-रे",
        "xai_saliency": "सैलिएंसी मैप",
        "xai_smoothgrad": "स्मूथग्रेड",
        "xai_overlay": "{method} ओवरले",
        "pdf_title": "X-Ray AI Consultant - निदान रिपोर्ट",
        "pdf_date": "दिनांक:",
        "pdf_model": "उपयोग किया गया AI मॉडल:",
        "pdf_diagnosis": "निदान: {label}",
        "pdf_confidence": "विश्वास स्तर: {confidence}%",
        "pdf_original": "मूल एक्स-रे",
        "pdf_heatmap": "XAI हीटमैप",
        "pdf_error_images": "छवियां लोड करने में त्रुटि",
        "chat_apikey_error": "GROQ_API_KEY कॉन्फ़िगर नहीं है",
    },
}


def get_text(key: str, lang: str = "es") -> str:
    texts = _TRANSLATIONS.get(lang, _TRANSLATIONS["es"])
    return texts.get(key, key)


def get_lang_from_cookie(request) -> str:
    lang = request.cookies.get("appLang", "es")
    if lang not in _VALID_LANGS:
        return "es"
    return lang
